# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digvijay Naruka
email: digvijay_naruka@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio of Digvijay Naruka, a computer science student from Alabama State university.
  His projects and experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  digvijayad
skills: Computer Science - Alabama State University

# Header Settings
set_blog: true                        # Display blog? 
header_bg: background-01.jpg          # Header background Image
header_bg_title: Background vector created by Starline - Freepik.com

# Footer settings
footer:                               #Footer Headers
  copyright: Email- MyFirstName_LastName@outlook.com
  location: Location
  social: Around the Web
  credits: ABOUT Digvijay
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# For more icons look at http://fontawesome.io/icons/#brand
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/4714773/digvijayad
  - title: google-plus
    url: #
  - title: bitbucket
    url: https://bitbucket.com/digvijayad
  - title: linkedin
    url: https://www.linkedin.com/in/digvijay-naruka/
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 915 S Jackson Street 
  - line: Montgomery, AL 36104

# Credits content
credits: 'Digvijay is a soon to be a graduate from Alabama State University, excited to participate in the real world.'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
